### ISSUE TITLE
How can I contribute?

### ISSUE THREAD

**Issue by davidkayce** [eXtern-OS/eXternOS-Base#2]
I came across your project while browsing for new Linux distros and I think it's something interesting. I would love to help in any way I can but I am having difficulty understanding how the different bits come together and where help would be needed. Could you consider having some markdown files explaining the architecture of the project and the state of the features so one can know where to jump in? Thanks 🙂

**Comment by anesuc** [comment]
Hi Dave!

At this current moment the project is undergoing a lot of changes that I would suggest you wait until that process is complete. As a result, there hasn't been much documentation etc set-up as a lot of things might be outdated by the time the changes are complete.

**Comment by anesuc** [comment]
I'll close this for now as there isn't much that can be done until then!

**Comment by davidkayce** [comment]
As an aside, have you considered [Neutralino](https://github.com/neutralinojs/neutralinojs) against NW.js. It is a lot newer but if something lightweight is important to you then I think it's worth a look. The evaluation against NW.js and electron can be seen here too: https://github.com/neutralinojs/evaluation
