### ISSUE TITLE
[Question] How do you compile extern-os?

### ISSUE THREAD

**Issue by TheMightyZucc** [eXtern-OS/eXternOS-Base#4]
I have experience in HTML, CSS and node-js but I've never worked on an OS before. How do you compile eXtern-OS?

**Comment by anesuc** [comment]
I gotta figure out a way to streamline this. But you can modify the squashfs directory and then compress this (you can look this up, can't do that for you atm). Once you've done that, copy it into the casper directory and name it `filesystem.squashfs` i.e  `casper/filesystem.squashfs`. And now generate an ISO of the live-iso directory. Alternatively you can get the eXtern OS live ISO and work backwards as it's the same contents and probably easier. Just decompress the squashfs and work from there. This is extremely outdated now as I have been looking into a way to do this without having to handle 1GB or more of data in a repo haha.
