### ISSUE TITLE
Sorry for opening such a silly issue, but when is the iso gonna get built?

### ISSUE THREAD

**Issue by jukfiuune** [eXtern-OS/eXternOS-Base#7]
Sorry, but if you can, please give an ETA

**Comment by anesuc** [comment]
Hi @jukfiuune !

The development for this had taken a break in the past 2 or so months as I needed to find a way to have more time to work on this as this is a rather large project and it was taking longer than it should to develop. This meant finding some ways to fund things with more time. There is some good developments on this but can't say anything yet until around end of this week. You can join this discord server for a more timely update: https://discord.gg/JB49CNZc
